development:
#  host: 'localhost'
  host: 'reunimosredis.rqzes9.0001.apse2.cache.amazonaws.com'
  port: '6379'
test:
  host: 'localhost'
  port: '6379'
production:
  host: 'reunimosredis.rqzes9.0001.apse2.cache.amazonaws.com'
  port: '6379'
